name: SimpleSurvival
main: net.SimpleSurvival.SimpleSurvival
version: 0.1-SNAPSHOT

permissions:
  gamemaster.*:
    description: The admin of the survival game.
    default: op

commands:
  survival:
    description: register or unregister from a game
    usage: "Usage: /survival <register|unregister> <gameID>"
    permission: gamemaster