name: SimpleSurvival
main: net.SimpleSurvival.SimpleSurvival
version: 0.1-SNAPSHOT

permissions:
  gamemaster.*:
    description: The admin of the survival game.
    default: op

commands:
  survival:
    description: register or unregister from a game
    usage: "Usage: /survival <register|unregister> <gameID>"
    permission: gamemaster
  warp:
    description: manually warp players to a game
    usage: "Usage: /warp <game>"
    permission: gamemaster
  start:
    description: manually start a game
    usage: "Usage: /start <game>"
    permission: gamemaster
  endall:
    description: end all games, queued and running"
    usage: "Usage: /endall"
    permission: gamemaster