name: SimpleSurvival
main: net.SimpleSurvival.SimpleSurvival
version: 0.1-SNAPSHOT
author: maldridge
authors: [justanull, geppettodivacin, ibrown]

permissions:
  SS.*:
    description: The admin of the survival game.
    default: op
  SS.player:
    description: The player of the game.
    default: true
commands:
  survival:
    description: register or unregister from a game
    usage: "Usage: /survival <register|unregister> <gameID>"
    permission: SS.player
  registerAll:
    description: registers all players to a game
    usage: "Usage: /registerAll <fromWorld> <toGame>"
    permission: SS.gamemaster
  deathmatch:
    description: starts a deathmatch
    usage: "Usage: /deathmatch [world] (no parameters gives world status)"
    permission: SS.gamemaster
  warp:
    description: manually warp players to a game
    usage: "Usage: /warp <game>"
    permission: SS.gamemaster
  start:
    description: manually start a game
    usage: "Usage: /start <game>"
    permission: SS.gamemaster
  endall:
    description: end all games, queued and running
    usage: "Usage: /endall"
    permission: SS.gamemaster
  addspawn:
    description: add a spawn to the temp list
    usage: "Usage: /addspawn"
    permission: SS.gamemaster
  dumpspawns:
    description: print all stored spawns
    usage: "Usage /dumpspawns"
    permission: SS.gamemaster
  clearspawns:
    description: clear temp spawn list
    usage: "Usage /clearspawns"
    permission: SS.gamemaster
  status:
    description: dump status
    usage: "Usage /status"
    permission: SS.gamemaster